CREATE TABLE accounts
(
    USER_ID    serial PRIMARY KEY,
    USERNAME   VARCHAR(50) UNIQUE  NOT NULL,
    PASSWORD   VARCHAR(50)         NOT NULL,
    EMAIL      VARCHAR(150) UNIQUE NOT NULL,
    CREATED_ON TIMESTAMP           NOT NULL
);